# 全连接神经网络进行鸢尾花分类

## 准备数据

In [18]:
import numpy as np
import tensorflow as tf
from sklearn.datasets import *
from sklearn.preprocessing import LabelBinarizer
from sklearn.cross_validation import train_test_split
import tensorflow as tf

In [2]:
dataSet = make_classification(n_classes=3, n_features=4, n_clusters_per_class=1, n_samples=500, random_state=2018, n_redundant=1, shuffle=1)
dataSet

(array([[-0.57735448, -1.32923192, -1.18540157, -0.29662364],
        [ 0.13115641, -1.15647866,  0.68250921, -1.06701086],
        [ 0.60609368,  0.15276936,  1.59648582,  0.77553312],
        ...,
        [ 0.12081775, -2.11301695,  0.92555748,  0.3152947 ],
        [ 0.94552668,  0.86050877,  2.31428667,  0.52105849],
        [-0.52171284, -1.16674083, -1.08090372,  1.14649076]]),
 array([1, 0, 2, 0, 0, 2, 2, 0, 2, 0, 1, 2, 2, 1, 0, 2, 1, 0, 0, 0, 0, 2,
        2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 1, 0, 2, 2, 1, 0, 1, 2, 2, 1, 0, 2,
        2, 1, 0, 1, 2, 0, 0, 1, 2, 0, 2, 1, 0, 2, 2, 1, 0, 2, 0, 1, 2, 1,
        0, 1, 0, 1, 1, 0, 0, 0, 2, 0, 2, 1, 2, 0, 2, 1, 1, 0, 1, 2, 1, 0,
        1, 0, 0, 1, 1, 2, 1, 2, 1, 1, 1, 0, 1, 2, 0, 0, 2, 2, 1, 0, 1, 2,
        0, 1, 1, 1, 1, 2, 2, 1, 2, 0, 2, 2, 0, 2, 1, 2, 1, 2, 1, 0, 0, 2,
        0, 2, 2, 0, 2, 0, 1, 2, 1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 2, 2, 1, 2,
        1, 0, 1, 1, 2, 2, 0, 1, 1, 1, 0, 0, 2, 2, 1, 0, 0, 1, 0, 0, 2, 1,
        0, 2, 2, 0, 2

用PCA降到2维看看数据分布

In [16]:
raw_y = LabelBinarizer().fit_transform(dataSet[1])
raw_y

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       ...,
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])

In [17]:
train_x, test_x, train_y, test_y = train_test_split(dataSet[0], raw_y, test_size=0.1)

## 搭建模型

In [ ]:
def add_layer(in_data, num_input, num_output, active_function=None):   #num_input:特征数, num_output:神经元数
    weights = tf.Variable(tf.random_normal((num_input, num_output)))
    bias = tf.Variable(tf.zeros((1, num_output)) + 0.5)
    result = tf.matmul(in_data, weights) + bias
    
    if active_function == None:
        return result
    else:
        return active_function(result)    #节点激活函数

In [22]:
num_feat = len(train_x[0])
input_x = tf.placeholder(tf.float32, [None, num_feat])
lay_0 = add_layer(input_x, 4, 10)
lay_pred = add_layer(lay_0, 10, 3, tf.nn.relu)

loss = tf.reduce_mean(tf.reduce_sum(abs(input_x - lay_pred), reduction_indices=1))
train_step = tf.train.GradientDescentOptimizer(0.08).minimize(loss)

with tf.Session() as sess:
    sess.r

NameError: name 'add_layer' is not defined