# 全连接神经网络进行鸢尾花分类

## 准备数据

In [1]:
import numpy as np
import tensorflow as tf
from sklearn.datasets import *
from sklearn.preprocessing import LabelBinarizer
from sklearn.cross_validation import train_test_split
import tensorflow as tf

D:\study\Anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
D:\study\Anaconda\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
dataSet = make_classification(n_classes=3, n_features=4, n_clusters_per_class=1, n_samples=500, random_state=2018, n_redundant=1, shuffle=1)
dataSet

(array([[-0.57735448, -1.32923192, -1.18540157, -0.29662364],
        [ 0.13115641, -1.15647866,  0.68250921, -1.06701086],
        [ 0.60609368,  0.15276936,  1.59648582,  0.77553312],
        ...,
        [ 0.12081775, -2.11301695,  0.92555748,  0.3152947 ],
        [ 0.94552668,  0.86050877,  2.31428667,  0.52105849],
        [-0.52171284, -1.16674083, -1.08090372,  1.14649076]]),
 array([1, 0, 2, 0, 0, 2, 2, 0, 2, 0, 1, 2, 2, 1, 0, 2, 1, 0, 0, 0, 0, 2,
        2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 1, 0, 2, 2, 1, 0, 1, 2, 2, 1, 0, 2,
        2, 1, 0, 1, 2, 0, 0, 1, 2, 0, 2, 1, 0, 2, 2, 1, 0, 2, 0, 1, 2, 1,
        0, 1, 0, 1, 1, 0, 0, 0, 2, 0, 2, 1, 2, 0, 2, 1, 1, 0, 1, 2, 1, 0,
        1, 0, 0, 1, 1, 2, 1, 2, 1, 1, 1, 0, 1, 2, 0, 0, 2, 2, 1, 0, 1, 2,
        0, 1, 1, 1, 1, 2, 2, 1, 2, 0, 2, 2, 0, 2, 1, 2, 1, 2, 1, 0, 0, 2,
        0, 2, 2, 0, 2, 0, 1, 2, 1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 2, 2, 1, 2,
        1, 0, 1, 1, 2, 2, 0, 1, 1, 1, 0, 0, 2, 2, 1, 0, 0, 1, 0, 0, 2, 1,
        0, 2, 2, 0, 2

用PCA降到2维看看数据分布

In [3]:
raw_y = LabelBinarizer().fit_transform(dataSet[1])
raw_y

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       ...,
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])

In [4]:
train_x, test_x, train_y, test_y = train_test_split(dataSet[0], raw_y, test_size=0.1)

## 搭建模型

In [5]:
def add_layer(in_data, num_input, num_output, active_function=None):   #num_input:特征数, num_output:神经元数
    weights = tf.Variable(tf.random_normal((num_input, num_output)))
    bias = tf.Variable(tf.zeros((1, num_output)) + 0.5)
    result = tf.matmul(in_data, weights) + bias
    
    if active_function == None:
        return result
    else:
        return active_function(result)    #节点激活函数

In [32]:
def train_model(num_neural=6):
    num_feat = len(train_x[0])
    num_class = len(set(dataSet[1]))
    input_x = tf.placeholder(tf.float32, [None, num_feat])
    input_y = tf.placeholder(tf.float32, [None, num_class])
    lay_0 = add_layer(input_x, num_feat, num_neural)
    lay_pred = add_layer(lay_0, num_neural, num_class, tf.nn.relu)

    loss = tf.reduce_mean(tf.reduce_sum(abs(input_y - lay_pred), reduction_indices=1))
    train_step = tf.train.GradientDescentOptimizer(0.08).minimize(loss)

    with tf.Session() as sess:
        sess.run(tf.initialize_all_variables())
        for step in range(3000):
            sess.run(train_step, feed_dict={input_x: train_x, input_y: train_y})
            if step % 50 == 0:
                print(sess.run(loss, feed_dict={input_x: train_x, input_y: train_y}))
                
train_model()

3.5109246
0.5325399
0.50614685
0.47707272
0.45550027
0.44156525
0.43020928
0.410304
0.40393928
0.40154546
0.39427185
0.3972909
0.39254764
0.3892948
0.3876309
0.3872673
0.38622028
0.38633534
0.38519585
0.38407794
0.38386706
0.383933
0.38452736
0.3837793
0.3838755
0.38483652
0.3847435
0.3839039
0.38347092
0.384012
0.38442838
0.38385183
0.3839556
0.38438198
0.3843172
0.38328817
0.38317826
0.38401678
0.3832422
0.38317508
0.38262028
0.3838209
0.3838678
0.38288385
0.38262948
0.38255838
0.38254544
0.3838966
0.38254762
0.38385534
0.38287503
0.3820298
0.38205245
0.3826623
0.3822726
0.38237512
0.38313547
0.38228416
0.38190702
0.38278568
